/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserCredentialRequestDTO
 */
export interface AddUserCredentialRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof AddUserCredentialRequestDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserCredentialRequestDTO
     */
    password: string;
}

/**
 * Check if a given object implements the AddUserCredentialRequestDTO interface.
 */
export function instanceOfAddUserCredentialRequestDTO(value: object): value is AddUserCredentialRequestDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AddUserCredentialRequestDTOFromJSON(json: any): AddUserCredentialRequestDTO {
    return AddUserCredentialRequestDTOFromJSONTyped(json, false);
}

export function AddUserCredentialRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserCredentialRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AddUserCredentialRequestDTOToJSON(json: any): AddUserCredentialRequestDTO {
    return AddUserCredentialRequestDTOToJSONTyped(json, false);
}

export function AddUserCredentialRequestDTOToJSONTyped(value?: AddUserCredentialRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

