/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUserEmailRequestDTO
 */
export interface ChangeUserEmailRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserEmailRequestDTO
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeUserEmailRequestDTO
     */
    newEmail: string;
}

/**
 * Check if a given object implements the ChangeUserEmailRequestDTO interface.
 */
export function instanceOfChangeUserEmailRequestDTO(value: object): value is ChangeUserEmailRequestDTO {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newEmail' in value) || value['newEmail'] === undefined) return false;
    return true;
}

export function ChangeUserEmailRequestDTOFromJSON(json: any): ChangeUserEmailRequestDTO {
    return ChangeUserEmailRequestDTOFromJSONTyped(json, false);
}

export function ChangeUserEmailRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUserEmailRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newEmail': json['newEmail'],
    };
}

export function ChangeUserEmailRequestDTOToJSON(json: any): ChangeUserEmailRequestDTO {
    return ChangeUserEmailRequestDTOToJSONTyped(json, false);
}

export function ChangeUserEmailRequestDTOToJSONTyped(value?: ChangeUserEmailRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newEmail': value['newEmail'],
    };
}

