/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUserPasswordRequestDTO
 */
export interface ChangeUserPasswordRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserPasswordRequestDTO
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeUserPasswordRequestDTO
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ChangeUserPasswordRequestDTO interface.
 */
export function instanceOfChangeUserPasswordRequestDTO(value: object): value is ChangeUserPasswordRequestDTO {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function ChangeUserPasswordRequestDTOFromJSON(json: any): ChangeUserPasswordRequestDTO {
    return ChangeUserPasswordRequestDTOFromJSONTyped(json, false);
}

export function ChangeUserPasswordRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUserPasswordRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function ChangeUserPasswordRequestDTOToJSON(json: any): ChangeUserPasswordRequestDTO {
    return ChangeUserPasswordRequestDTOToJSONTyped(json, false);
}

export function ChangeUserPasswordRequestDTOToJSONTyped(value?: ChangeUserPasswordRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

