/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmEmailInput
 */
export interface ConfirmEmailInput {
    /**
     * 
     * @type {string}
     * @memberof ConfirmEmailInput
     */
    token: string;
}

/**
 * Check if a given object implements the ConfirmEmailInput interface.
 */
export function instanceOfConfirmEmailInput(value: object): value is ConfirmEmailInput {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ConfirmEmailInputFromJSON(json: any): ConfirmEmailInput {
    return ConfirmEmailInputFromJSONTyped(json, false);
}

export function ConfirmEmailInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmailInput {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ConfirmEmailInputToJSON(json: any): ConfirmEmailInput {
    return ConfirmEmailInputToJSONTyped(json, false);
}

export function ConfirmEmailInputToJSONTyped(value?: ConfirmEmailInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

