/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePostInputRepliedPostId } from './CreatePostInputRepliedPostId';
import {
    CreatePostInputRepliedPostIdFromJSON,
    CreatePostInputRepliedPostIdFromJSONTyped,
    CreatePostInputRepliedPostIdToJSON,
    CreatePostInputRepliedPostIdToJSONTyped,
} from './CreatePostInputRepliedPostId';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface CreatePostInput
 */
export interface CreatePostInput {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof CreatePostInput
     */
    userId: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {string}
     * @memberof CreatePostInput
     */
    content: string;
    /**
     * 
     * @type {CreatePostInputRepliedPostId}
     * @memberof CreatePostInput
     */
    repliedPostId?: CreatePostInputRepliedPostId | null;
}

/**
 * Check if a given object implements the CreatePostInput interface.
 */
export function instanceOfCreatePostInput(value: object): value is CreatePostInput {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreatePostInputFromJSON(json: any): CreatePostInput {
    return CreatePostInputFromJSONTyped(json, false);
}

export function CreatePostInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostInput {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['userId']),
        'content': json['content'],
        'repliedPostId': json['repliedPostId'] == null ? undefined : CreatePostInputRepliedPostIdFromJSON(json['repliedPostId']),
    };
}

export function CreatePostInputToJSON(json: any): CreatePostInput {
    return CreatePostInputToJSONTyped(json, false);
}

export function CreatePostInputToJSONTyped(value?: CreatePostInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['userId']),
        'content': value['content'],
        'repliedPostId': CreatePostInputRepliedPostIdToJSON(value['repliedPostId']),
    };
}

