/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePostInputRepliedPostId
 */
export interface CreatePostInputRepliedPostId {
}

/**
 * Check if a given object implements the CreatePostInputRepliedPostId interface.
 */
export function instanceOfCreatePostInputRepliedPostId(value: object): value is CreatePostInputRepliedPostId {
    return true;
}

export function CreatePostInputRepliedPostIdFromJSON(json: any): CreatePostInputRepliedPostId {
    return CreatePostInputRepliedPostIdFromJSONTyped(json, false);
}

export function CreatePostInputRepliedPostIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostInputRepliedPostId {
    return json;
}

export function CreatePostInputRepliedPostIdToJSON(json: any): CreatePostInputRepliedPostId {
    return CreatePostInputRepliedPostIdToJSONTyped(json, false);
}

export function CreatePostInputRepliedPostIdToJSONTyped(value?: CreatePostInputRepliedPostId | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

