/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserInput
 */
export interface CreateUserInput {
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserInput
     */
    birthDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    bio: string | null;
}

/**
 * Check if a given object implements the CreateUserInput interface.
 */
export function instanceOfCreateUserInput(value: object): value is CreateUserInput {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    return true;
}

export function CreateUserInputFromJSON(json: any): CreateUserInput {
    return CreateUserInputFromJSONTyped(json, false);
}

export function CreateUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserInput {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
        'bio': json['bio'],
    };
}

export function CreateUserInputToJSON(json: any): CreateUserInput {
    return CreateUserInputToJSONTyped(json, false);
}

export function CreateUserInputToJSONTyped(value?: CreateUserInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'name': value['name'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'bio': value['bio'],
    };
}

