/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface CreatedResponseDTO
 */
export interface CreatedResponseDTO {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof CreatedResponseDTO
     */
    newId: HashtagsFindTrendingWindowInHoursParameter;
}

/**
 * Check if a given object implements the CreatedResponseDTO interface.
 */
export function instanceOfCreatedResponseDTO(value: object): value is CreatedResponseDTO {
    if (!('newId' in value) || value['newId'] === undefined) return false;
    return true;
}

export function CreatedResponseDTOFromJSON(json: any): CreatedResponseDTO {
    return CreatedResponseDTOFromJSONTyped(json, false);
}

export function CreatedResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'newId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['newId']),
    };
}

export function CreatedResponseDTOToJSON(json: any): CreatedResponseDTO {
    return CreatedResponseDTOToJSONTyped(json, false);
}

export function CreatedResponseDTOToJSONTyped(value?: CreatedResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['newId']),
    };
}

