/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHashtagInput
 */
export interface CreateHashtagInput {
    /**
     * 
     * @type {string}
     * @memberof CreateHashtagInput
     */
    tag: string;
}

/**
 * Check if a given object implements the CreateHashtagInput interface.
 */
export function instanceOfCreateHashtagInput(value: object): value is CreateHashtagInput {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function CreateHashtagInputFromJSON(json: any): CreateHashtagInput {
    return CreateHashtagInputFromJSONTyped(json, false);
}

export function CreateHashtagInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHashtagInput {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
    };
}

export function CreateHashtagInputToJSON(json: any): CreateHashtagInput {
    return CreateHashtagInputToJSONTyped(json, false);
}

export function CreateHashtagInputToJSONTyped(value?: CreateHashtagInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
    };
}

