/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Hashtag } from './Hashtag';
import {
    HashtagFromJSON,
    HashtagFromJSONTyped,
    HashtagToJSON,
    HashtagToJSONTyped,
} from './Hashtag';
import type { TrendingHashtagMetadata } from './TrendingHashtagMetadata';
import {
    TrendingHashtagMetadataFromJSON,
    TrendingHashtagMetadataFromJSONTyped,
    TrendingHashtagMetadataToJSON,
    TrendingHashtagMetadataToJSONTyped,
} from './TrendingHashtagMetadata';

/**
 * 
 * @export
 * @interface FindTrendingHashtagsOutput
 */
export interface FindTrendingHashtagsOutput {
    /**
     * 
     * @type {Array<Hashtag>}
     * @memberof FindTrendingHashtagsOutput
     */
    hashtags: Array<Hashtag>;
    /**
     * 
     * @type {Array<TrendingHashtagMetadata>}
     * @memberof FindTrendingHashtagsOutput
     */
    trendingMetadata: Array<TrendingHashtagMetadata>;
}

/**
 * Check if a given object implements the FindTrendingHashtagsOutput interface.
 */
export function instanceOfFindTrendingHashtagsOutput(value: object): value is FindTrendingHashtagsOutput {
    if (!('hashtags' in value) || value['hashtags'] === undefined) return false;
    if (!('trendingMetadata' in value) || value['trendingMetadata'] === undefined) return false;
    return true;
}

export function FindTrendingHashtagsOutputFromJSON(json: any): FindTrendingHashtagsOutput {
    return FindTrendingHashtagsOutputFromJSONTyped(json, false);
}

export function FindTrendingHashtagsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindTrendingHashtagsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtags': ((json['hashtags'] as Array<any>).map(HashtagFromJSON)),
        'trendingMetadata': ((json['trendingMetadata'] as Array<any>).map(TrendingHashtagMetadataFromJSON)),
    };
}

export function FindTrendingHashtagsOutputToJSON(json: any): FindTrendingHashtagsOutput {
    return FindTrendingHashtagsOutputToJSONTyped(json, false);
}

export function FindTrendingHashtagsOutputToJSONTyped(value?: FindTrendingHashtagsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtags': ((value['hashtags'] as Array<any>).map(HashtagToJSON)),
        'trendingMetadata': ((value['trendingMetadata'] as Array<any>).map(TrendingHashtagMetadataToJSON)),
    };
}

