/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
    PostToJSONTyped,
} from './Post';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface FindManyPostsOutput
 */
export interface FindManyPostsOutput {
    /**
     * 
     * @type {Array<Post>}
     * @memberof FindManyPostsOutput
     */
    posts: Array<Post>;
    /**
     * 
     * @type {Array<HashtagsFindTrendingWindowInHoursParameter>}
     * @memberof FindManyPostsOutput
     */
    notFoundIds: Array<HashtagsFindTrendingWindowInHoursParameter>;
}

/**
 * Check if a given object implements the FindManyPostsOutput interface.
 */
export function instanceOfFindManyPostsOutput(value: object): value is FindManyPostsOutput {
    if (!('posts' in value) || value['posts'] === undefined) return false;
    if (!('notFoundIds' in value) || value['notFoundIds'] === undefined) return false;
    return true;
}

export function FindManyPostsOutputFromJSON(json: any): FindManyPostsOutput {
    return FindManyPostsOutputFromJSONTyped(json, false);
}

export function FindManyPostsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindManyPostsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': ((json['posts'] as Array<any>).map(PostFromJSON)),
        'notFoundIds': ((json['notFoundIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterFromJSON)),
    };
}

export function FindManyPostsOutputToJSON(json: any): FindManyPostsOutput {
    return FindManyPostsOutputToJSONTyped(json, false);
}

export function FindManyPostsOutputToJSONTyped(value?: FindManyPostsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'posts': ((value['posts'] as Array<any>).map(PostToJSON)),
        'notFoundIds': ((value['notFoundIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterToJSON)),
    };
}

