/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTokenOutput
 */
export interface GenerateTokenOutput {
    /**
     * 
     * @type {string}
     * @memberof GenerateTokenOutput
     */
    token: string;
}

/**
 * Check if a given object implements the GenerateTokenOutput interface.
 */
export function instanceOfGenerateTokenOutput(value: object): value is GenerateTokenOutput {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GenerateTokenOutputFromJSON(json: any): GenerateTokenOutput {
    return GenerateTokenOutputFromJSONTyped(json, false);
}

export function GenerateTokenOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTokenOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GenerateTokenOutputToJSON(json: any): GenerateTokenOutput {
    return GenerateTokenOutputToJSONTyped(json, false);
}

export function GenerateTokenOutputToJSONTyped(value?: GenerateTokenOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

