/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTokenInput
 */
export interface GenerateTokenInput {
    /**
     * 
     * @type {string}
     * @memberof GenerateTokenInput
     */
    usernameOrEmail: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateTokenInput
     */
    password: string;
}

/**
 * Check if a given object implements the GenerateTokenInput interface.
 */
export function instanceOfGenerateTokenInput(value: object): value is GenerateTokenInput {
    if (!('usernameOrEmail' in value) || value['usernameOrEmail'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function GenerateTokenInputFromJSON(json: any): GenerateTokenInput {
    return GenerateTokenInputFromJSONTyped(json, false);
}

export function GenerateTokenInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTokenInput {
    if (json == null) {
        return json;
    }
    return {
        
        'usernameOrEmail': json['usernameOrEmail'],
        'password': json['password'],
    };
}

export function GenerateTokenInputToJSON(json: any): GenerateTokenInput {
    return GenerateTokenInputToJSONTyped(json, false);
}

export function GenerateTokenInputToJSONTyped(value?: GenerateTokenInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usernameOrEmail': value['usernameOrEmail'],
        'password': value['password'],
    };
}

