/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostMetadata } from './PostMetadata';
import {
    PostMetadataFromJSON,
    PostMetadataFromJSONTyped,
    PostMetadataToJSON,
    PostMetadataToJSONTyped,
} from './PostMetadata';

/**
 * 
 * @export
 * @interface GetPostsMetadataOutput
 */
export interface GetPostsMetadataOutput {
    /**
     * 
     * @type {Array<PostMetadata>}
     * @memberof GetPostsMetadataOutput
     */
    ownPosts: Array<PostMetadata>;
    /**
     * 
     * @type {Array<PostMetadata>}
     * @memberof GetPostsMetadataOutput
     */
    mentionPosts: Array<PostMetadata>;
}

/**
 * Check if a given object implements the GetPostsMetadataOutput interface.
 */
export function instanceOfGetPostsMetadataOutput(value: object): value is GetPostsMetadataOutput {
    if (!('ownPosts' in value) || value['ownPosts'] === undefined) return false;
    if (!('mentionPosts' in value) || value['mentionPosts'] === undefined) return false;
    return true;
}

export function GetPostsMetadataOutputFromJSON(json: any): GetPostsMetadataOutput {
    return GetPostsMetadataOutputFromJSONTyped(json, false);
}

export function GetPostsMetadataOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostsMetadataOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'ownPosts': ((json['ownPosts'] as Array<any>).map(PostMetadataFromJSON)),
        'mentionPosts': ((json['mentionPosts'] as Array<any>).map(PostMetadataFromJSON)),
    };
}

export function GetPostsMetadataOutputToJSON(json: any): GetPostsMetadataOutput {
    return GetPostsMetadataOutputToJSONTyped(json, false);
}

export function GetPostsMetadataOutputToJSONTyped(value?: GetPostsMetadataOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ownPosts': ((value['ownPosts'] as Array<any>).map(PostMetadataToJSON)),
        'mentionPosts': ((value['mentionPosts'] as Array<any>).map(PostMetadataToJSON)),
    };
}

