/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface Hashtag
 */
export interface Hashtag {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof Hashtag
     */
    id?: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {Date}
     * @memberof Hashtag
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Hashtag
     */
    tag: string;
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof Hashtag
     */
    postsCount?: HashtagsFindTrendingWindowInHoursParameter;
}

/**
 * Check if a given object implements the Hashtag interface.
 */
export function instanceOfHashtag(value: object): value is Hashtag {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function HashtagFromJSON(json: any): Hashtag {
    return HashtagFromJSONTyped(json, false);
}

export function HashtagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hashtag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : HashtagsFindTrendingWindowInHoursParameterFromJSON(json['id']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'tag': json['tag'],
        'postsCount': json['postsCount'] == null ? undefined : HashtagsFindTrendingWindowInHoursParameterFromJSON(json['postsCount']),
    };
}

export function HashtagToJSON(json: any): Hashtag {
    return HashtagToJSONTyped(json, false);
}

export function HashtagToJSONTyped(value?: Hashtag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': HashtagsFindTrendingWindowInHoursParameterToJSON(value['id']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'tag': value['tag'],
        'postsCount': HashtagsFindTrendingWindowInHoursParameterToJSON(value['postsCount']),
    };
}

