/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashtagsFindTrendingWindowInHoursParameter
 */
export interface HashtagsFindTrendingWindowInHoursParameter {
}

/**
 * Check if a given object implements the HashtagsFindTrendingWindowInHoursParameter interface.
 */
export function instanceOfHashtagsFindTrendingWindowInHoursParameter(value: object): value is HashtagsFindTrendingWindowInHoursParameter {
    return true;
}

export function HashtagsFindTrendingWindowInHoursParameterFromJSON(json: any): HashtagsFindTrendingWindowInHoursParameter {
    return HashtagsFindTrendingWindowInHoursParameterFromJSONTyped(json, false);
}

export function HashtagsFindTrendingWindowInHoursParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagsFindTrendingWindowInHoursParameter {
    return json;
}

export function HashtagsFindTrendingWindowInHoursParameterToJSON(json: any): HashtagsFindTrendingWindowInHoursParameter {
    return HashtagsFindTrendingWindowInHoursParameterToJSONTyped(json, false);
}

export function HashtagsFindTrendingWindowInHoursParameterToJSONTyped(value?: HashtagsFindTrendingWindowInHoursParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

