/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface PostMetadata
 */
export interface PostMetadata {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof PostMetadata
     */
    postId: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {Date}
     * @memberof PostMetadata
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof PostMetadata
     */
    relationToUser: number;
}

/**
 * Check if a given object implements the PostMetadata interface.
 */
export function instanceOfPostMetadata(value: object): value is PostMetadata {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('relationToUser' in value) || value['relationToUser'] === undefined) return false;
    return true;
}

export function PostMetadataFromJSON(json: any): PostMetadata {
    return PostMetadataFromJSONTyped(json, false);
}

export function PostMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['postId']),
        'createdAt': (new Date(json['createdAt'])),
        'relationToUser': json['relationToUser'],
    };
}

export function PostMetadataToJSON(json: any): PostMetadata {
    return PostMetadataToJSONTyped(json, false);
}

export function PostMetadataToJSONTyped(value?: PostMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['postId']),
        'createdAt': value['createdAt'].toISOString(),
        'relationToUser': value['relationToUser'],
    };
}

