/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePostInputRepliedPostId } from './CreatePostInputRepliedPostId';
import {
    CreatePostInputRepliedPostIdFromJSON,
    CreatePostInputRepliedPostIdFromJSONTyped,
    CreatePostInputRepliedPostIdToJSON,
    CreatePostInputRepliedPostIdToJSONTyped,
} from './CreatePostInputRepliedPostId';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof Post
     */
    id?: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof Post
     */
    authorUserId?: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Post
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<HashtagsFindTrendingWindowInHoursParameter>}
     * @memberof Post
     */
    mentionedUsersIds?: Array<HashtagsFindTrendingWindowInHoursParameter>;
    /**
     * 
     * @type {Array<HashtagsFindTrendingWindowInHoursParameter>}
     * @memberof Post
     */
    mentionedHashtagsIds?: Array<HashtagsFindTrendingWindowInHoursParameter>;
    /**
     * 
     * @type {CreatePostInputRepliedPostId}
     * @memberof Post
     */
    repliedPostId?: CreatePostInputRepliedPostId | null;
    /**
     * 
     * @type {Array<HashtagsFindTrendingWindowInHoursParameter>}
     * @memberof Post
     */
    replyingPostsIds?: Array<HashtagsFindTrendingWindowInHoursParameter>;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : HashtagsFindTrendingWindowInHoursParameterFromJSON(json['id']),
        'authorUserId': json['authorUserId'] == null ? undefined : HashtagsFindTrendingWindowInHoursParameterFromJSON(json['authorUserId']),
        'content': json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'mentionedUsersIds': json['mentionedUsersIds'] == null ? undefined : ((json['mentionedUsersIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterFromJSON)),
        'mentionedHashtagsIds': json['mentionedHashtagsIds'] == null ? undefined : ((json['mentionedHashtagsIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterFromJSON)),
        'repliedPostId': json['repliedPostId'] == null ? undefined : CreatePostInputRepliedPostIdFromJSON(json['repliedPostId']),
        'replyingPostsIds': json['replyingPostsIds'] == null ? undefined : ((json['replyingPostsIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterFromJSON)),
    };
}

export function PostToJSON(json: any): Post {
    return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': HashtagsFindTrendingWindowInHoursParameterToJSON(value['id']),
        'authorUserId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['authorUserId']),
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'mentionedUsersIds': value['mentionedUsersIds'] == null ? undefined : ((value['mentionedUsersIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterToJSON)),
        'mentionedHashtagsIds': value['mentionedHashtagsIds'] == null ? undefined : ((value['mentionedHashtagsIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterToJSON)),
        'repliedPostId': CreatePostInputRepliedPostIdToJSON(value['repliedPostId']),
        'replyingPostsIds': value['replyingPostsIds'] == null ? undefined : ((value['replyingPostsIds'] as Array<any>).map(HashtagsFindTrendingWindowInHoursParameterToJSON)),
    };
}

