/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserInput
 */
export interface RegisterUserInput {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserInput
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserInput
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof RegisterUserInput
     */
    birthDate: Date;
}

/**
 * Check if a given object implements the RegisterUserInput interface.
 */
export function instanceOfRegisterUserInput(value: object): value is RegisterUserInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    return true;
}

export function RegisterUserInputFromJSON(json: any): RegisterUserInput {
    return RegisterUserInputFromJSONTyped(json, false);
}

export function RegisterUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'username': json['username'],
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
    };
}

export function RegisterUserInputToJSON(json: any): RegisterUserInput {
    return RegisterUserInputToJSONTyped(json, false);
}

export function RegisterUserInputToJSONTyped(value?: RegisterUserInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'username': value['username'],
        'name': value['name'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
    };
}

