/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface SendEmailConfirmationInput
 */
export interface SendEmailConfirmationInput {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof SendEmailConfirmationInput
     */
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

/**
 * Check if a given object implements the SendEmailConfirmationInput interface.
 */
export function instanceOfSendEmailConfirmationInput(value: object): value is SendEmailConfirmationInput {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SendEmailConfirmationInputFromJSON(json: any): SendEmailConfirmationInput {
    return SendEmailConfirmationInputFromJSONTyped(json, false);
}

export function SendEmailConfirmationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailConfirmationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['userId']),
    };
}

export function SendEmailConfirmationInputToJSON(json: any): SendEmailConfirmationInput {
    return SendEmailConfirmationInputToJSONTyped(json, false);
}

export function SendEmailConfirmationInputToJSONTyped(value?: SendEmailConfirmationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['userId']),
    };
}

