/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrendingHashtagMetadataScore } from './TrendingHashtagMetadataScore';
import {
    TrendingHashtagMetadataScoreFromJSON,
    TrendingHashtagMetadataScoreFromJSONTyped,
    TrendingHashtagMetadataScoreToJSON,
    TrendingHashtagMetadataScoreToJSONTyped,
} from './TrendingHashtagMetadataScore';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface TrendingHashtagMetadata
 */
export interface TrendingHashtagMetadata {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof TrendingHashtagMetadata
     */
    hashtagId: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {TrendingHashtagMetadataScore}
     * @memberof TrendingHashtagMetadata
     */
    score: TrendingHashtagMetadataScore;
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof TrendingHashtagMetadata
     */
    totalPosts: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof TrendingHashtagMetadata
     */
    totalUsers: HashtagsFindTrendingWindowInHoursParameter;
}

/**
 * Check if a given object implements the TrendingHashtagMetadata interface.
 */
export function instanceOfTrendingHashtagMetadata(value: object): value is TrendingHashtagMetadata {
    if (!('hashtagId' in value) || value['hashtagId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('totalPosts' in value) || value['totalPosts'] === undefined) return false;
    if (!('totalUsers' in value) || value['totalUsers'] === undefined) return false;
    return true;
}

export function TrendingHashtagMetadataFromJSON(json: any): TrendingHashtagMetadata {
    return TrendingHashtagMetadataFromJSONTyped(json, false);
}

export function TrendingHashtagMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingHashtagMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtagId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['hashtagId']),
        'score': TrendingHashtagMetadataScoreFromJSON(json['score']),
        'totalPosts': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['totalPosts']),
        'totalUsers': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['totalUsers']),
    };
}

export function TrendingHashtagMetadataToJSON(json: any): TrendingHashtagMetadata {
    return TrendingHashtagMetadataToJSONTyped(json, false);
}

export function TrendingHashtagMetadataToJSONTyped(value?: TrendingHashtagMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtagId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['hashtagId']),
        'score': TrendingHashtagMetadataScoreToJSON(value['score']),
        'totalPosts': HashtagsFindTrendingWindowInHoursParameterToJSON(value['totalPosts']),
        'totalUsers': HashtagsFindTrendingWindowInHoursParameterToJSON(value['totalUsers']),
    };
}

