/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendingHashtagMetadataScore
 */
export interface TrendingHashtagMetadataScore {
}

/**
 * Check if a given object implements the TrendingHashtagMetadataScore interface.
 */
export function instanceOfTrendingHashtagMetadataScore(value: object): value is TrendingHashtagMetadataScore {
    return true;
}

export function TrendingHashtagMetadataScoreFromJSON(json: any): TrendingHashtagMetadataScore {
    return TrendingHashtagMetadataScoreFromJSONTyped(json, false);
}

export function TrendingHashtagMetadataScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingHashtagMetadataScore {
    return json;
}

export function TrendingHashtagMetadataScoreToJSON(json: any): TrendingHashtagMetadataScore {
    return TrendingHashtagMetadataScoreToJSONTyped(json, false);
}

export function TrendingHashtagMetadataScoreToJSONTyped(value?: TrendingHashtagMetadataScore | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

