/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRequestDTO
 */
export interface UpdateUserRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequestDTO
     */
    bio: string | null;
}

/**
 * Check if a given object implements the UpdateUserRequestDTO interface.
 */
export function instanceOfUpdateUserRequestDTO(value: object): value is UpdateUserRequestDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    return true;
}

export function UpdateUserRequestDTOFromJSON(json: any): UpdateUserRequestDTO {
    return UpdateUserRequestDTOFromJSONTyped(json, false);
}

export function UpdateUserRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bio': json['bio'],
    };
}

export function UpdateUserRequestDTOToJSON(json: any): UpdateUserRequestDTO {
    return UpdateUserRequestDTOToJSONTyped(json, false);
}

export function UpdateUserRequestDTOToJSONTyped(value?: UpdateUserRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'bio': value['bio'],
    };
}

