/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface UserFollow
 */
export interface UserFollow {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof UserFollow
     */
    userId: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {Date}
     * @memberof UserFollow
     */
    beingFollowedSince: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserFollow
     */
    followerSince: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserFollow
     */
    isFollowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserFollow
     */
    isFollower?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserFollow
     */
    isMutual?: boolean;
}

/**
 * Check if a given object implements the UserFollow interface.
 */
export function instanceOfUserFollow(value: object): value is UserFollow {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('beingFollowedSince' in value) || value['beingFollowedSince'] === undefined) return false;
    if (!('followerSince' in value) || value['followerSince'] === undefined) return false;
    return true;
}

export function UserFollowFromJSON(json: any): UserFollow {
    return UserFollowFromJSONTyped(json, false);
}

export function UserFollowFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFollow {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['userId']),
        'beingFollowedSince': (json['beingFollowedSince'] == null ? null : new Date(json['beingFollowedSince'])),
        'followerSince': (json['followerSince'] == null ? null : new Date(json['followerSince'])),
        'isFollowed': json['isFollowed'] == null ? undefined : json['isFollowed'],
        'isFollower': json['isFollower'] == null ? undefined : json['isFollower'],
        'isMutual': json['isMutual'] == null ? undefined : json['isMutual'],
    };
}

export function UserFollowToJSON(json: any): UserFollow {
    return UserFollowToJSONTyped(json, false);
}

export function UserFollowToJSONTyped(value?: UserFollow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': HashtagsFindTrendingWindowInHoursParameterToJSON(value['userId']),
        'beingFollowedSince': value['beingFollowedSince'] == null ? value['beingFollowedSince'] : value['beingFollowedSince'].toISOString(),
        'followerSince': value['followerSince'] == null ? value['followerSince'] : value['followerSince'].toISOString(),
        'isFollowed': value['isFollowed'],
        'isFollower': value['isFollower'],
        'isMutual': value['isMutual'],
    };
}

