/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HashtagsFindTrendingWindowInHoursParameter } from './HashtagsFindTrendingWindowInHoursParameter';
import {
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSONTyped,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSONTyped,
} from './HashtagsFindTrendingWindowInHoursParameter';

/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {HashtagsFindTrendingWindowInHoursParameter}
     * @memberof UserDTO
     */
    id: HashtagsFindTrendingWindowInHoursParameter;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    bio: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    avatarPictureURL: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    coverPictureURL: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserDTO
     */
    birthDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDTO
     */
    joinedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDTO
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserDTO
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the UserDTO interface.
 */
export function instanceOfUserDTO(value: object): value is UserDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('bio' in value) || value['bio'] === undefined) return false;
    if (!('avatarPictureURL' in value) || value['avatarPictureURL'] === undefined) return false;
    if (!('coverPictureURL' in value) || value['coverPictureURL'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': HashtagsFindTrendingWindowInHoursParameterFromJSON(json['id']),
        'username': json['username'],
        'name': json['name'],
        'bio': json['bio'],
        'avatarPictureURL': json['avatarPictureURL'],
        'coverPictureURL': json['coverPictureURL'],
        'birthDate': (new Date(json['birthDate'])),
        'joinedAt': (new Date(json['joinedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function UserDTOToJSON(json: any): UserDTO {
    return UserDTOToJSONTyped(json, false);
}

export function UserDTOToJSONTyped(value?: UserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': HashtagsFindTrendingWindowInHoursParameterToJSON(value['id']),
        'username': value['username'],
        'name': value['name'],
        'bio': value['bio'],
        'avatarPictureURL': value['avatarPictureURL'],
        'coverPictureURL': value['coverPictureURL'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'joinedAt': value['joinedAt'].toISOString().substring(0,10),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

