/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenerateTokenInput,
  GenerateTokenOutput,
  ProblemDetails,
} from '../models/index';
import {
    GenerateTokenInputFromJSON,
    GenerateTokenInputToJSON,
    GenerateTokenOutputFromJSON,
    GenerateTokenOutputToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface AuthLoginRequest {
    generateTokenInput: GenerateTokenInput;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authLoginRaw(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateTokenOutput>> {
        if (requestParameters['generateTokenInput'] == null) {
            throw new runtime.RequiredError(
                'generateTokenInput',
                'Required parameter "generateTokenInput" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateTokenInputToJSON(requestParameters['generateTokenInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateTokenOutputFromJSON(jsonValue));
    }

    /**
     */
    async authLogin(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateTokenOutput> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authValidateTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/validate-token`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authValidateToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authValidateTokenRaw(initOverrides);
    }

}
