/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateHashtagInput,
  CreatedResponseDTO,
  FindTrendingHashtagsOutput,
  Hashtag,
  HashtagsFindTrendingWindowInHoursParameter,
  ProblemDetails,
} from '../models/index';
import {
    CreateHashtagInputFromJSON,
    CreateHashtagInputToJSON,
    CreatedResponseDTOFromJSON,
    CreatedResponseDTOToJSON,
    FindTrendingHashtagsOutputFromJSON,
    FindTrendingHashtagsOutputToJSON,
    HashtagFromJSON,
    HashtagToJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface HashtagsCreateRequest {
    createHashtagInput: CreateHashtagInput;
}

export interface HashtagsFindByIdRequest {
    id: number;
}

export interface HashtagsFindByTagRequest {
    tag: string;
}

export interface HashtagsFindTrendingRequest {
    windowInHours?: HashtagsFindTrendingWindowInHoursParameter;
}

/**
 * 
 */
export class HashtagsApi extends runtime.BaseAPI {

    /**
     */
    async hashtagsCreateRaw(requestParameters: HashtagsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedResponseDTO>> {
        if (requestParameters['createHashtagInput'] == null) {
            throw new runtime.RequiredError(
                'createHashtagInput',
                'Required parameter "createHashtagInput" was null or undefined when calling hashtagsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/hashtags`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateHashtagInputToJSON(requestParameters['createHashtagInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async hashtagsCreate(requestParameters: HashtagsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedResponseDTO> {
        const response = await this.hashtagsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hashtagsFindByIdRaw(requestParameters: HashtagsFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Hashtag>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling hashtagsFindById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hashtags/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HashtagFromJSON(jsonValue));
    }

    /**
     */
    async hashtagsFindById(requestParameters: HashtagsFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Hashtag> {
        const response = await this.hashtagsFindByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hashtagsFindByTagRaw(requestParameters: HashtagsFindByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Hashtag>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling hashtagsFindByTag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hashtags/{tag}`;
        urlPath = urlPath.replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HashtagFromJSON(jsonValue));
    }

    /**
     */
    async hashtagsFindByTag(requestParameters: HashtagsFindByTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Hashtag> {
        const response = await this.hashtagsFindByTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async hashtagsFindTrendingRaw(requestParameters: HashtagsFindTrendingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindTrendingHashtagsOutput>> {
        const queryParameters: any = {};

        if (requestParameters['windowInHours'] != null) {
            queryParameters['window_in_hours'] = requestParameters['windowInHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hashtags/trending`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindTrendingHashtagsOutputFromJSON(jsonValue));
    }

    /**
     */
    async hashtagsFindTrending(requestParameters: HashtagsFindTrendingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindTrendingHashtagsOutput> {
        const response = await this.hashtagsFindTrendingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
