/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePostInput,
  CreatedResponseDTO,
  FindManyPostsOutput,
  HashtagsFindTrendingWindowInHoursParameter,
  Post,
  ProblemDetails,
} from '../models/index';
import {
    CreatePostInputFromJSON,
    CreatePostInputToJSON,
    CreatedResponseDTOFromJSON,
    CreatedResponseDTOToJSON,
    FindManyPostsOutputFromJSON,
    FindManyPostsOutputToJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    PostFromJSON,
    PostToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface PostsCreateRequest {
    createPostInput: CreatePostInput;
}

export interface PostsDeleteRequest {
    postId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface PostsFindByIdRequest {
    postId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface PostsFindManyByIdRequest {
    postIds?: Array<HashtagsFindTrendingWindowInHoursParameter>;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     */
    async postsCreateRaw(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedResponseDTO>> {
        if (requestParameters['createPostInput'] == null) {
            throw new runtime.RequiredError(
                'createPostInput',
                'Required parameter "createPostInput" was null or undefined when calling postsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/posts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostInputToJSON(requestParameters['createPostInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async postsCreate(requestParameters: PostsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedResponseDTO> {
        const response = await this.postsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postsDeleteRaw(requestParameters: PostsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/{postId}`;
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postsDelete(requestParameters: PostsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async postsFindByIdRaw(requestParameters: PostsFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postsFindById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/{postId}`;
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     */
    async postsFindById(requestParameters: PostsFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.postsFindByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postsFindManyByIdRaw(requestParameters: PostsFindManyByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindManyPostsOutput>> {
        const queryParameters: any = {};

        if (requestParameters['postIds'] != null) {
            queryParameters['post_ids'] = requestParameters['postIds'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindManyPostsOutputFromJSON(jsonValue));
    }

    /**
     */
    async postsFindManyById(requestParameters: PostsFindManyByIdRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindManyPostsOutput> {
        const response = await this.postsFindManyByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
