/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmEmailInput,
  CreatedResponseDTO,
  ProblemDetails,
  RegisterUserInput,
  SendEmailConfirmationInput,
} from '../models/index';
import {
    ConfirmEmailInputFromJSON,
    ConfirmEmailInputToJSON,
    CreatedResponseDTOFromJSON,
    CreatedResponseDTOToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    RegisterUserInputFromJSON,
    RegisterUserInputToJSON,
    SendEmailConfirmationInputFromJSON,
    SendEmailConfirmationInputToJSON,
} from '../models/index';

export interface UserRegistrationConfirmEmailRequest {
    confirmEmailInput: ConfirmEmailInput;
}

export interface UserRegistrationRegisterUserRequest {
    registerUserInput: RegisterUserInput;
}

export interface UserRegistrationSendEmailRequest {
    sendEmailConfirmationInput: SendEmailConfirmationInput;
}

/**
 * 
 */
export class UserRegistrationApi extends runtime.BaseAPI {

    /**
     */
    async userRegistrationConfirmEmailRaw(requestParameters: UserRegistrationConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['confirmEmailInput'] == null) {
            throw new runtime.RequiredError(
                'confirmEmailInput',
                'Required parameter "confirmEmailInput" was null or undefined when calling userRegistrationConfirmEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-registration/confirm-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmEmailInputToJSON(requestParameters['confirmEmailInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userRegistrationConfirmEmail(requestParameters: UserRegistrationConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userRegistrationConfirmEmailRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userRegistrationRegisterUserRaw(requestParameters: UserRegistrationRegisterUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedResponseDTO>> {
        if (requestParameters['registerUserInput'] == null) {
            throw new runtime.RequiredError(
                'registerUserInput',
                'Required parameter "registerUserInput" was null or undefined when calling userRegistrationRegisterUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-registration`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterUserInputToJSON(requestParameters['registerUserInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async userRegistrationRegisterUser(requestParameters: UserRegistrationRegisterUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedResponseDTO> {
        const response = await this.userRegistrationRegisterUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userRegistrationSendEmailRaw(requestParameters: UserRegistrationSendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sendEmailConfirmationInput'] == null) {
            throw new runtime.RequiredError(
                'sendEmailConfirmationInput',
                'Required parameter "sendEmailConfirmationInput" was null or undefined when calling userRegistrationSendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-registration/send-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendEmailConfirmationInputToJSON(requestParameters['sendEmailConfirmationInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userRegistrationSendEmail(requestParameters: UserRegistrationSendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userRegistrationSendEmailRaw(requestParameters, initOverrides);
    }

}
