/* tslint:disable */
/* eslint-disable */
/**
 * Infra | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserCredentialRequestDTO,
  ChangeUserEmailRequestDTO,
  ChangeUserPasswordRequestDTO,
  CreateUserInput,
  CreatedResponseDTO,
  GetPostsMetadataOutput,
  HashtagsFindTrendingWindowInHoursParameter,
  ProblemDetails,
  UpdateUserRequestDTO,
  UserDTO,
  UserFollow,
} from '../models/index';
import {
    AddUserCredentialRequestDTOFromJSON,
    AddUserCredentialRequestDTOToJSON,
    ChangeUserEmailRequestDTOFromJSON,
    ChangeUserEmailRequestDTOToJSON,
    ChangeUserPasswordRequestDTOFromJSON,
    ChangeUserPasswordRequestDTOToJSON,
    CreateUserInputFromJSON,
    CreateUserInputToJSON,
    CreatedResponseDTOFromJSON,
    CreatedResponseDTOToJSON,
    GetPostsMetadataOutputFromJSON,
    GetPostsMetadataOutputToJSON,
    HashtagsFindTrendingWindowInHoursParameterFromJSON,
    HashtagsFindTrendingWindowInHoursParameterToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UpdateUserRequestDTOFromJSON,
    UpdateUserRequestDTOToJSON,
    UserDTOFromJSON,
    UserDTOToJSON,
    UserFollowFromJSON,
    UserFollowToJSON,
} from '../models/index';

export interface UserFollowsGetRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UserFollowsIncludeRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    targetUserId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UserFollowsRemoveRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    targetUserId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UserProfilePicturesDeleteAvatarRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UserProfilePicturesDeleteCoverRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UserProfilePicturesPutAvatarRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    picture?: Blob;
}

export interface UserProfilePicturesPutCoverRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    picture?: Blob;
}

export interface UsersAddCredentialRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    addUserCredentialRequestDTO: AddUserCredentialRequestDTO;
}

export interface UsersCreateRequest {
    createUserInput: CreateUserInput;
}

export interface UsersDeleteRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UsersFindByIdOrUsernameRequest {
    userId: string;
}

export interface UsersFindManyRequest {
    userIds?: Array<HashtagsFindTrendingWindowInHoursParameter>;
}

export interface UsersGetPostsMetadataRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
}

export interface UsersUpdateRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    updateUserRequestDTO: UpdateUserRequestDTO;
}

export interface UsersUpdateEmailRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    changeUserEmailRequestDTO: ChangeUserEmailRequestDTO;
}

export interface UsersUpdatePasswordRequest {
    userId: HashtagsFindTrendingWindowInHoursParameter;
    changeUserPasswordRequestDTO: ChangeUserPasswordRequestDTO;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     */
    async userFollowsGetRaw(requestParameters: UserFollowsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserFollow>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userFollowsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/follows`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFollowFromJSON));
    }

    /**
     */
    async userFollowsGet(requestParameters: UserFollowsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserFollow>> {
        const response = await this.userFollowsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userFollowsIncludeRaw(requestParameters: UserFollowsIncludeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userFollowsInclude().'
            );
        }

        if (requestParameters['targetUserId'] == null) {
            throw new runtime.RequiredError(
                'targetUserId',
                'Required parameter "targetUserId" was null or undefined when calling userFollowsInclude().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/follows/{targetUserId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"targetUserId"}}`, encodeURIComponent(String(requestParameters['targetUserId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userFollowsInclude(requestParameters: UserFollowsIncludeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userFollowsIncludeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userFollowsRemoveRaw(requestParameters: UserFollowsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userFollowsRemove().'
            );
        }

        if (requestParameters['targetUserId'] == null) {
            throw new runtime.RequiredError(
                'targetUserId',
                'Required parameter "targetUserId" was null or undefined when calling userFollowsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/follows/{targetUserId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"targetUserId"}}`, encodeURIComponent(String(requestParameters['targetUserId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userFollowsRemove(requestParameters: UserFollowsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userFollowsRemoveRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userProfilePicturesDeleteAvatarRaw(requestParameters: UserProfilePicturesDeleteAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userProfilePicturesDeleteAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/profile-pictures/avatar`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userProfilePicturesDeleteAvatar(requestParameters: UserProfilePicturesDeleteAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userProfilePicturesDeleteAvatarRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userProfilePicturesDeleteCoverRaw(requestParameters: UserProfilePicturesDeleteCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userProfilePicturesDeleteCover().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/profile-pictures/cover`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userProfilePicturesDeleteCover(requestParameters: UserProfilePicturesDeleteCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userProfilePicturesDeleteCoverRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userProfilePicturesPutAvatarRaw(requestParameters: UserProfilePicturesPutAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userProfilePicturesPutAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['picture'] != null) {
            formParams.append('Picture', requestParameters['picture'] as any);
        }


        let urlPath = `/users/{userId}/profile-pictures/avatar`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userProfilePicturesPutAvatar(requestParameters: UserProfilePicturesPutAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userProfilePicturesPutAvatarRaw(requestParameters, initOverrides);
    }

    /**
     */
    async userProfilePicturesPutCoverRaw(requestParameters: UserProfilePicturesPutCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userProfilePicturesPutCover().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['picture'] != null) {
            formParams.append('Picture', requestParameters['picture'] as any);
        }


        let urlPath = `/users/{userId}/profile-pictures/cover`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async userProfilePicturesPutCover(requestParameters: UserProfilePicturesPutCoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.userProfilePicturesPutCoverRaw(requestParameters, initOverrides);
    }

    /**
     */
    async usersAddCredentialRaw(requestParameters: UsersAddCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersAddCredential().'
            );
        }

        if (requestParameters['addUserCredentialRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'addUserCredentialRequestDTO',
                'Required parameter "addUserCredentialRequestDTO" was null or undefined when calling usersAddCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}/credential`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserCredentialRequestDTOToJSON(requestParameters['addUserCredentialRequestDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async usersAddCredential(requestParameters: UsersAddCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersAddCredentialRaw(requestParameters, initOverrides);
    }

    /**
     */
    async usersCreateRaw(requestParameters: UsersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatedResponseDTO>> {
        if (requestParameters['createUserInput'] == null) {
            throw new runtime.RequiredError(
                'createUserInput',
                'Required parameter "createUserInput" was null or undefined when calling usersCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserInputToJSON(requestParameters['createUserInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatedResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async usersCreate(requestParameters: UsersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatedResponseDTO> {
        const response = await this.usersCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersDeleteRaw(requestParameters: UsersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async usersDelete(requestParameters: UsersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async usersFindByIdOrUsernameRaw(requestParameters: UsersFindByIdOrUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersFindByIdOrUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue));
    }

    /**
     */
    async usersFindByIdOrUsername(requestParameters: UsersFindByIdOrUsernameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO> {
        const response = await this.usersFindByIdOrUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersFindManyRaw(requestParameters: UsersFindManyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['userIds'] != null) {
            queryParameters['user_ids'] = requestParameters['userIds'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserDTOFromJSON));
    }

    /**
     */
    async usersFindMany(requestParameters: UsersFindManyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserDTO>> {
        const response = await this.usersFindManyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersGetPostsMetadataRaw(requestParameters: UsersGetPostsMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPostsMetadataOutput>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersGetPostsMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/posts-metadata`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPostsMetadataOutputFromJSON(jsonValue));
    }

    /**
     */
    async usersGetPostsMetadata(requestParameters: UsersGetPostsMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPostsMetadataOutput> {
        const response = await this.usersGetPostsMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersUpdateRaw(requestParameters: UsersUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUpdate().'
            );
        }

        if (requestParameters['updateUserRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'updateUserRequestDTO',
                'Required parameter "updateUserRequestDTO" was null or undefined when calling usersUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserRequestDTOToJSON(requestParameters['updateUserRequestDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async usersUpdate(requestParameters: UsersUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersUpdateRaw(requestParameters, initOverrides);
    }

    /**
     */
    async usersUpdateEmailRaw(requestParameters: UsersUpdateEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUpdateEmail().'
            );
        }

        if (requestParameters['changeUserEmailRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'changeUserEmailRequestDTO',
                'Required parameter "changeUserEmailRequestDTO" was null or undefined when calling usersUpdateEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}/email`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeUserEmailRequestDTOToJSON(requestParameters['changeUserEmailRequestDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async usersUpdateEmail(requestParameters: UsersUpdateEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersUpdateEmailRaw(requestParameters, initOverrides);
    }

    /**
     */
    async usersUpdatePasswordRaw(requestParameters: UsersUpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUpdatePassword().'
            );
        }

        if (requestParameters['changeUserPasswordRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'changeUserPasswordRequestDTO',
                'Required parameter "changeUserPasswordRequestDTO" was null or undefined when calling usersUpdatePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{userId}/password`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeUserPasswordRequestDTOToJSON(requestParameters['changeUserPasswordRequestDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async usersUpdatePassword(requestParameters: UsersUpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersUpdatePasswordRaw(requestParameters, initOverrides);
    }

}
